
general {
        colors = true
        interval = 5
}

#order += "disk /home"
#order += "ethernet eth0"
#order += "cpu_usage"
order += "tztime local"

ethernet eth0 {
        format_up = "E: up"
        format_down = "E: down"
}

tztime local {
        format = "%d.%m.%Y %H:%M"
}

cpu_usage {
        format = "CPU: %usage"
}

disk "/home" {
        format = "/home: %avail (%percentage_avail)"
}

